<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('course_id')->constrained()->cascadeOnDelete();
            $table->foreignId('enrollment_id')->nullable()->constrained()->nullOnDelete();
            $table->string('merchant_ref_number')->unique();               // generated by us, sent to Fawry
            $table->string('fawry_reference_number')->nullable()->index(); // returned by Fawry
            $table->decimal('amount', 10, 2);
            $table->enum('status', ['pending', 'paid', 'unpaid', 'expired', 'failed', 'canceled', 'refunded'])
                ->default('pending')
                ->index();
            $table->string('payment_method')->nullable(); // PAYATFAWRY, CARD, MWALLET...
            $table->json('fawry_response')->nullable();   // raw callback payload for auditing
            $table->timestamp('paid_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
